### ISSUE TITLE
interaction with pruneExpiredEntries 

### ISSUE THREAD

**Issue by dbu** [Toflar/psr6-symfony-http-cache-store#2]
after looking through the code, i realized that the store calls prune on itself. but that method then uses a counter to decide whether the cache should be pruned or not. i think it would be better to have that method simply execute `$this->cache->prune();`. the code that is now pruneExpiredEntries should be a private method (e.g. `periodicAutoPrune`) that is called during write  and handles the counter update and in turn calls pruneExpiredEntries when the threshold is reached.

that way, i can disable auto pruning, but still prune from outside, e.g. in a cronjob or with a special request and another listener.

**Comment by Toflar** [comment]
That's indeed a very good objection! Implemented in https://github.com/Toflar/psr6-symfony-http-cache-store/commit/f47551c3d4a1d8c2be9e7fe3e8f48461a09f313b.

**Comment by dbu** [comment]
thanks, excellent!
