### ISSUE TITLE
Support for Symfony 2.8?

### ISSUE THREAD

**Issue by rkconsulting** [Toflar/psr6-symfony-http-cache-store#23]
Hi there,

does this component support Symfony 2.8?

Thanks,
-Rob

**Comment by goetas** [comment]
you can read it here https://github.com/Toflar/psr6-symfony-http-cache-store/blob/6a595527a227ee78fe2b81378ed488715f23c303/composer.json#L12, it seems that 2.8 is not supported

**Comment by Toflar** [comment]
No, Symfony 2.8 is an unmaintained Symfony version anyway so I don't see why that would make any sense.
