### ISSUE TITLE
Different locks prune and clear

### ISSUE THREAD

**Issue by Mynyx** [Toflar/psr6-symfony-http-cache-store#29]
It is correct, that ``prune`` and ``clear`` use different locks? I don't think these should overlap?

https://github.com/Toflar/psr6-symfony-http-cache-store/blob/5364b76033d23801f5dd39e6ccc21fec3d4ccf96/src/Psr6Store.php#L412-L419

https://github.com/Toflar/psr6-symfony-http-cache-store/blob/5364b76033d23801f5dd39e6ccc21fec3d4ccf96/src/Psr6Store.php#L431-L434

And if it would be correct, the comment in the ``clear`` function should be amended.

**Comment by Toflar** [comment]
Yeah I think they should not interfere. Implemented in 5ecf8f1cc13a696662da71594ca6739cfae0fbb9.
