### ISSUE TITLE
Header toflar-psr6cache-requested-uri

### ISSUE THREAD

**Issue by BugBuster1701** [Toflar/psr6-symfony-http-cache-store#32]
The debug header is displayed when a cache entry is written the first time.

![toflar-psr6cache-request-uri](https://user-images.githubusercontent.com/1218809/80116333-23259980-8586-11ea-9d35-76f1d40e5b4b.png)

**Comment by Toflar** [comment]
Fixed in 286b1b853b68ac2698fa2c6270b9210ad39ce412.
