### ISSUE TITLE
[BC-Break] Psr6Store::getCacheKey() marked as @internal

### ISSUE THREAD

**Issue by stlrnz** [Toflar/psr6-symfony-http-cache-store#35]
Hi,

in https://github.com/Toflar/psr6-symfony-http-cache-store/commit/de1c7ecc3cf3c90eb0dd6752c51731e56bcda726 you marked Psr6Store::getCacheKey() as internal. In your commit message you even describe that this is a BC-Break. You argued that "Calling those should be considered a bug.".

I strongly disagree. Like described in https://github.com/Toflar/psr6-symfony-http-cache-store/issues/6 I override this method to implement some custom logic (normalizing URL before generating the key). Would you consider to remove the internal declaration?

Thank you.

**Comment by Toflar** [comment]
Ah, I forgot about that. I'll remove it again in the next release and add some tests so I don't accidentally build it back again :)
I won't release a new version just to remove it though. But feel free to continue using it.

**Comment by Toflar** [comment]
Ah stupid me forgot about it in 3.0.0. I've pushed it to the hotfix branch in ae2e8924bb76d73aa04d235f13d8b7fd96da5aaa so I don't forget about it again in the next bugfix release.
Sorry about that. Closing it now :)
