### ISSUE TITLE
Cache miss when using FilesystemTagAwareAdapter

### ISSUE THREAD

**Issue by cirykpopeye** [Toflar/psr6-symfony-http-cache-store#37]
Within `src/Psr6Store.php` on L97 there's check wether or not Symfony is 4.3+, if so use the `FilesystemTagAwareAdapter` as cache otherwise use the `TagAwareAdapter`.

On my shared hosting I have the issue that there's always a cache miss when using the `FilesystemTagAwareAdapter` and therefor never hits the cache. 

Uncommenting this line and caching starts working. I temp forced `TagAwareAdapter` using the `$options` to fix my problem. 

No idea what could be related due to this not working, but I'm willing to share the needed info/help.

**Comment by Toflar** [comment]
Sounds like a bug in `FilesystemTagAwareAdapter` then? Are you using the latest version of `symfony/cache`?
