### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by ioniks** [Toflar/psr6-symfony-http-cache-store#43]
Hi,

i have tested default integration of the bundle and the performance is the same without cache.

When i use default symfony http cache with reverse proxy the reponse time after cached query is about 7 to 15 ms max and when i use this bundle it's about 150 ms.

I'm on prod env localy for test.

Thanks for your help.

**Comment by Toflar** [comment]
Sorry but I'll need a lot more information than just "performance is the same without cache" if you want me to help you on that.

**Comment by ioniks** [comment]
Problem solved, performance issue come from render_esi and no default TTL on HttpCache Kernel.

Thanks for you quickly response 👍
