### ISSUE TITLE
Increase the prune threshold

### ISSUE THREAD

**Issue by leofeyer** [Toflar/psr6-symfony-http-cache-store#5]
Can you explain why you have set the `prune_threshold` parameter to every 500 write operations by default? This seems very low to me.

If my website has 5.000 pages, the cache will have been pruned 10 times before all the page have been indexed. And if my pages use fragments, the cache might have been pruned even more often.

Or did I get this wrong?

**Comment by Toflar** [comment]
That's correct. And I don't really think it's a problem to prune 10 times for 5000 entries. It's a matter of finding a sane default and I just think there are more applications with 1 - 1000 entries than 1000 - 100 000 because the more entries you have, the likelier it is that you use a different proxy solution such as Varnish.

**Comment by Toflar** [comment]
BTW: I'm having no problems at all changing this default value. We should just find a sane default. It can always be adjusted for the specific application. What do you think @dbu? Is 500 too low?

**Comment by dbu** [comment]
This mechanism is like a pure-mans cron, it hijacks one request thread to do a background task. Applications should ideally run a cron job that calls prune on the configured cache on a time-based interval.

I have no idea if 500 is a good value or not, but i think it depends a lot. If you have pages of 100k that are cached, there will be a prune after 50M have been written. and this only counts on cache misses that lead to writes, not on cache hits neither on uncacheable results. there is potential that even with 500, prune is not called often enough... i would leave it as is - the prune operation should also not be too expensive i would hope.

@leofeyer you can pass the prune_threshold with a different value, if your scenario leads to lots of cache writes and you can't set up a cron that prunes the cache.

**Comment by leofeyer** [comment]
Setting up a cron job to prune the cache involves creating a command that the cron job can execute, correct?

**Comment by Toflar** [comment]
Yes.

**Comment by leofeyer** [comment]
Should we provide such a command?

**Comment by Toflar** [comment]
We cannot provide a general one as the application does not know about the store at all.

**Comment by leofeyer** [comment]
I meant in Contao. 😄 Sorry for being unclear.

Anyway, we should not discuss this here, therefore I'm closing the ticket.
