### ISSUE TITLE
Custom CacheKey

### ISSUE THREAD

**Issue by stlrnz** [Toflar/psr6-symfony-http-cache-store#6]
I'd like to extend the class Psr6Store to implement a custom getCacheKey() method (I need some custom logic here to increase my hit rate).
However, Psr6Store is declared as final, so there is no possibility to do that. Any chance to change that?

I think this could be useful for other users, too (e.g. to strip host name or parameters from the request).

**Comment by Toflar** [comment]
The cache is declared `final` on purpose because I absolutely don't want anybody to change the behaviour. We're talking about following the HTTP spec here.

**Comment by stlrnz** [comment]
Sure about that. I dont want to change the logic how the request is handled. All I want to do is implement a custom logic to generate the cache key (The same thing I could do in Varnish using hash_data in vcl_hash).

For my application I know the best how to generate that key.
E.g. you are stripping the scheme to handle http and https the same by default. Why are you doing this? I can think of a scenario where an application is accessible by both http and https. Assuming this application is generating absolute urls the implemented strategy will cause some trouble.

I can think of many other scenarios where it could be helpful to change the generation of that key. E.g. ignoring host names for applications accessible from multiple urls or ignoring some random parameters added by strangers to the url to skip the cache.
I hope you understand my point.

**Comment by Toflar** [comment]
> E.g. you are stripping the scheme to handle http and https the same by default. Why are you doing this?

Because the default one does was well: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/HttpCache/Store.php#L311


> I hope you understand my point.

Sure! My point is that I want to be able to provide as little extension points as possible so it's easier for me to provide BC :-) Feel free to provide a PR with the changes you need!

**Comment by stlrnz** [comment]
But the default implementation gives you the option to override the generateCacheKey() method: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/HttpCache/Store.php#L428

I understand your point of minimizing the extension points to reduce the effort of maintenance. But you should beware of providing not enough extentions point, too. And for my case, this is really important (I cannot use your package without modifying the cache key as I'm migrating from the default implementation using a custom key).

What do you think about an additional option "generate_cache_key" where you can optionally provide a callback to generate the key?

**Comment by Toflar** [comment]
> What do you think about an additional option "generate_cache_key" where you can optionally provide a callback to generate the key?

I think in that case I'd rather remove the `final` and make sure everything that's internal is kept `private` and only the things you really need are `protected`.

**Comment by stlrnz** [comment]
But changing the accessibility of methods would be a BC break, too.

**Comment by Toflar** [comment]
No? The class was `final` so far, nobody could've extended it :)

**Comment by stlrnz** [comment]
Buf if you would change `getCacheKey()` from `public` to `protected` would be a BC break. I thought you would suggest that.

**Comment by Toflar** [comment]
Ah, no it's public at the moment for unit test purposes. You don't need to change anything for this method then. I was talking about other ones in case you need anything else :)

**Comment by stlrnz** [comment]
Ok. In my case I don't have to override any of your private methods. So I think we can keep them private. You don't have any protected methods, so wo don't have to worry about them. Changing public methods would be a BC break, so we should keep them as they are.

The only thing we can do is removing the `final`.

**Comment by Toflar** [comment]
I've checked it all locally and you're right. I've just released version 1.1.0. Enjoy 😄

**Comment by stlrnz** [comment]
Thank you! :+1:
