### ISSUE TITLE
Missing symfony/options-resolver dependency

### ISSUE THREAD

**Issue by stlrnz** [Toflar/psr6-symfony-http-cache-store#7]
In the class `Psr6Store` you are using the symfony `OptionsResolver` component. But you are not requiring it in your `composer.json` file.

Please add the missing dependency.

**Comment by Toflar** [comment]
Fixed with https://github.com/Toflar/psr6-symfony-http-cache-store/commit/02c4275c31cc10923df4aff75c3af6151c77b983
