### ISSUE TITLE
Make directory name configurable

### ISSUE THREAD

**Issue by trickreich** [Toflar/psr6-symfony-http-cache-store#9]
I think we have talked on the SymfonyCon Lisbon already about this topic (but not 100% sure about this).
In my opinion it would be great to make the directory name configurable.

Here an example why such a feature would be great:
![image](https://user-images.githubusercontent.com/16644200/51842487-488b0f80-2311-11e9-9d89-936eee48701e.png)

What do you think about such a feature?

**Comment by Toflar** [comment]
You can pass your own cache and configure it the way you want to :) I think yet another option would just overcomplicate things a bit.

**Comment by trickreich** [comment]
I know, I've done it with `var/cache/http_cache/prod` but the store is adding one more folder.
I think following line is doing this: https://github.com/Toflar/psr6-symfony-http-cache-store/blob/master/src/Psr6Store.php#L122

**Comment by Toflar** [comment]
I don‘t understand the question. If you want to configure it completely on your own, pass your own cache instance using the `cache` option.

**Comment by trickreich** [comment]
Sorry.. a bit confusing question.
I'm creating an own store with the option `cache_directory`.
https://github.com/sulu/sulu/pull/4348/files#diff-ce6c813eee980d3476e2017a1c3a6d2eR76

But the store adds one more folder to this `cache_directory` path named `http_cache`.
In my case this lead to following structure: `var/cache/http_cache/prod/http_cache`.

**Comment by Toflar** [comment]
Yes I know, that‘s the default. Apart from looking strange there‘s no downside really. As I said, I don‘t want to introduce yet another configuration option because there‘s already enough to customize it to whatever cache you want to.

**Comment by trickreich** [comment]
Ok, thanks for your answers and time :+1:
